name: flutter_app_ui
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  nested: ^1.0.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/e_commerce_app/e_commerce_image/
     - assets/e_commerce_app/e_commerce_jsons/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-Regular.ttf
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-Black.ttf
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-Bold.ttf
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-ExtraBold.ttf
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-ExtraLight.ttf
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-Light.ttf
         - asset: assets/e_commerce_app/e_commerce_fonts/Inter-Medium.ttf
